name: Elixir CI

on:
  push:
    branches: [master, stable]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres_version: [13, 14, 15]

    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      clickhouse:
        image: clickhouse/clickhouse-server:23.3.7.5-alpine
        ports:
          - 8123:8123
        env:
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{steps.versions.outputs.elixir}}
          otp-version: ${{ steps.versions.outputs.erlang}}
      - name: Restore dependencies cache
        uses: buildjet/cache@v4
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-v7-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v7-
      - name: Install dependencies
        run: mix deps.get && npm install --prefix ./tracker
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Check Compile Warnings
        run: mix compile --warnings-as-errors --all-warnings
      - name: Generate tracker files
        run: npm run deploy --prefix ./tracker
      - name: Check Credo Warnings
        run: mix credo diff --from-git-merge-base origin/master
      - name: Run tests
        run: mix test --include slow --max-failures 1 --warnings-as-errors
      - name: Run tests (small build)
        run: MIX_ENV=small_test mix test --include slow --max-failures 1 --warnings-as-errors
      - name: Start MinIO (for S3 tests)
        run: docker run -d -p 9000:9000 minio/minio server /data
      - name: Create s3://imports bucket
        run: aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://imports
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_EC2_METADATA_DISABLED: true
      - name: Run tests (S3)
        run: mix test --only minio --max-failures 1 --warnings-as-errors
        env:
          S3_HOST_FOR_CLICKHOUSE: 172.17.0.1
      - name: Check Dialyzer
        run: mix dialyzer
env:
  MIX_ENV: test
